export const initialScoreboardData: ScoreboardData = {
    common: {
        homeTeamName: "Team 1",
        homeTeamScore: '00',
        homeTeamColor: '',
        homeTeamAvatar: '',
        awayTeamName: 'Team 2',
        awayTeamScore: '00',
        awayTeamColor: '00',
        awayTeamAvatar: '',
        matchName: "matchName",
        isImageShow: true,
        matchQuarter: '0'
    },
    Universal: {

    },
    soccer: {

    },
    volleyBall: {
        homeTeamSetScore: "00",
        awayTeamSetScore: "00",
    },

    billiard: {
        inning: "00",
        set: "00"
    },
    basketBall: {
        homeTeamFoul: "00",
        awayTeamFoul: "00"
    },
    baseBall: {
        inning: "0",
        isTop: true,
        out: "00",
        ball: "00",
        strike: "00",
        base1: true,
        base2: true,
        base3: true,
    },
    golfTotal: {
        players: [
            {
                playerName: 'Player 1',
                score: [
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                ],
                scoreIn: '0',
                scoreOut: '0',
                scoreTotal: '0',
            },
            {
                playerName: 'Player 2',
                score: [
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                ],
                scoreIn: '0',
                scoreOut: '0',
                scoreTotal: '0',
            },
            {
                playerName: 'Player 3',
                score: [
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                ],
                scoreIn: '0',
                scoreOut: '0',
                scoreTotal: '0',
            },
            {
                playerName: 'Player 4',
                score: [
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                ],
                scoreIn: '0',
                scoreOut: '0',
                scoreTotal: '0',
            },
        ],
        par1: "0",
        par2: "0",
        par3: "0",
        par4: "0",
        par5: "0",
        par6: "0",
        par7: "0",
        par8: "0",
        par9: "0",
        par10: "0",
        par11: "0",
        par12: "0",
        par13: "0",
        par14: "0",
        par15: "0",
        par16: "0",
        par17: "0",
        par18: "0",
        parIn: "0",
        parOut: "0",
        parTotal: "0",
        halfSetToggle: true,
        holeDistance: "0",
        holeNumber: "0",
    },
    cricket: {
        homeTeamOut: "0",
        over: "0",
        batsman1name: "",
        batsman1Score: "0",
        batsman1Hit: "0",
        batsman2name: "",
        batsman2Score: "0",
        batsman2Hit: "0",
        bowlerName: "",
        bowlerScore: "0",
        bowlerOut: "0",
        target: "0",
        total: "0",
        balls: "0"
    },

    football: {
        forthDown: "0",
        yardToGo: "0",
        isHomePossession: true,
        homeTeamTimeOut: "0",
        awayTeamTimeOut: "0",
    },
    tennis: {

    }, time: {

    },
    setting: {
        theme: 'universal',
        type: ScoreboardType
    },
};

